"""Scoring rules, pinned against the numbers that shipped.

scoring_parity.json was generated by executing the browser's scoring.js while
both implementations existed, to prove the Python port changed nobody's score.
That changeover is done and the JavaScript copy is gone, so the fixtures can no
longer be regenerated -- they are now a frozen baseline.

They are kept because that is exactly what makes them useful: 352 cases
recording what every combination of time, wrong guesses, hint and hard mode was
worth on the day the server took over. A change here means real scores move, and
should be a decision rather than an accident.
"""

import json
from pathlib import Path

import pytest
from scoring import (
    BASE,
    HARD_MULTIPLIER,
    HINT_PEN,
    MISPLACED_PEN,
    SCORE_FLOOR,
    TIME_GRACE,
    WRONG_PEN,
    calculate_score,
    calculate_streaks,
    score_breakdown,
)

PARITY = json.loads((Path(__file__).parent / "fixtures" / "scoring_parity.json").read_text())


def _case_id(case):
    i = case["input"]
    return (
        f"{i['result']}-t{i['time_seconds']}-w{i['wrong_guesses']}"
        f"{'-hint' if i['hint_used'] else ''}{'-hard' if i['hard_mode'] else ''}"
    )


class TestScoresHaveNotMoved:
    @pytest.mark.parametrize("case", PARITY["score"], ids=_case_id)
    def test_score_matches_the_shipped_baseline(self, case):
        i = case["input"]
        assert (
            calculate_score(
                result=i["result"],
                time_seconds=i["time_seconds"],
                wrong_guesses=i["wrong_guesses"],
                hint_used=i["hint_used"],
                hard_mode=i["hard_mode"],
            )
            == case["expected"]
        )

    @pytest.mark.parametrize(
        "case", PARITY["streaks"], ids=lambda c: "-".join(c["input"]) or "empty"
    )
    def test_streaks_match_the_shipped_baseline(self, case):
        assert calculate_streaks(case["input"]) == case["expected"]

    def test_the_fixtures_cover_the_interesting_edges(self):
        """Guards the guard: a truncated fixture file would pass everything above."""
        assert len(PARITY["score"]) >= 300
        expected = {c["expected"] for c in PARITY["score"]}
        assert 0 in expected, "no losses covered"
        assert BASE in expected, "no perfect win covered"
        assert SCORE_FLOOR in expected, "the score floor is never reached"
        assert round(SCORE_FLOOR * HARD_MULTIPLIER) in expected, "floored hard-mode win missing"


class TestScoreRules:
    """The behaviour the parity fixtures encode, written out readably."""

    WIN = {
        "result": "win",
        "time_seconds": 10,
        "wrong_guesses": 0,
        "hint_used": False,
        "hard_mode": False,
    }

    def test_a_loss_scores_zero(self):
        assert calculate_score(**{**self.WIN, "result": "loss"}) == 0

    def test_a_perfect_win_scores_the_base(self):
        assert calculate_score(**self.WIN) == BASE

    def test_no_penalty_up_to_the_grace_boundary(self):
        assert calculate_score(**{**self.WIN, "time_seconds": TIME_GRACE}) == BASE

    def test_time_is_charged_per_second_past_grace(self):
        assert calculate_score(**{**self.WIN, "time_seconds": TIME_GRACE + 40}) == BASE - 40

    def test_penalties_stack(self):
        score = calculate_score(
            **{
                **self.WIN,
                "time_seconds": TIME_GRACE + 100,
                "wrong_guesses": 1,
                "hint_used": True,
            }
        )
        assert score == BASE - 100 - WRONG_PEN - HINT_PEN

    def test_a_slow_win_never_drops_below_the_floor(self):
        assert calculate_score(**{**self.WIN, "time_seconds": 10_000}) == SCORE_FLOOR

    def test_hard_mode_multiplies_after_the_floor(self):
        score = calculate_score(**{**self.WIN, "time_seconds": 10_000, "hard_mode": True})
        assert score == round(SCORE_FLOOR * HARD_MULTIPLIER)

    def test_every_score_is_an_integer(self):
        for time_seconds in (0, 31, 77, 450):
            for hard_mode in (False, True):
                score = calculate_score(
                    **{**self.WIN, "time_seconds": time_seconds, "hard_mode": hard_mode}
                )
                assert isinstance(score, int)


class TestScoreBreakdown:
    def test_reports_each_penalty_separately(self):
        assert score_breakdown(
            time_seconds=TIME_GRACE + 25, wrong_guesses=2, hint_used=True, hard_mode=False
        ) == {
            "base": BASE,
            "time_pen": 25,
            "hint_pen": HINT_PEN,
            "wrong_pen": 2 * WRONG_PEN,
            "misplaced_pen": 0,
            "hard_mode": False,
        }

    @pytest.mark.parametrize(
        "time_seconds,wrong_guesses,hint_used,hard_mode",
        [
            (5, 0, False, False),
            (120, 2, True, False),
            (10_000, 2, True, False),
            (60, 0, False, True),
            (10_000, 0, True, True),
        ],
    )
    def test_reconciles_with_calculate_score(
        self, time_seconds, wrong_guesses, hint_used, hard_mode
    ):
        parts = score_breakdown(
            time_seconds=time_seconds,
            wrong_guesses=wrong_guesses,
            hint_used=hint_used,
            hard_mode=hard_mode,
        )
        floored = max(
            SCORE_FLOOR,
            parts["base"] - parts["time_pen"] - parts["hint_pen"] - parts["wrong_pen"],
        )
        expected = round(floored * HARD_MULTIPLIER) if hard_mode else floored

        assert (
            calculate_score(
                result="win",
                time_seconds=time_seconds,
                wrong_guesses=wrong_guesses,
                hint_used=hint_used,
                hard_mode=hard_mode,
            )
            == expected
        )


class TestTheMisplacementPenalty:
    """A right team in the wrong slot costs points, not a life.

    The life part is in test_sessions. This is the other half: without a cost,
    anyone who knew the teams could permute them until everything turned green,
    and the order is the game.
    """

    def test_a_misplacement_costs_points(self):
        clean = calculate_score("win", 0, 0, False, False)
        with_one = calculate_score("win", 0, 0, False, False, misplaced_guesses=1)
        assert clean - with_one == MISPLACED_PEN

    def test_it_costs_less_than_a_wrong_answer(self):
        # Knowing a team and misplacing it is better play than not knowing it.
        assert MISPLACED_PEN < WRONG_PEN

    def test_penalties_accumulate(self):
        assert (
            calculate_score("win", 0, 0, False, False, misplaced_guesses=4)
            == BASE - 4 * MISPLACED_PEN
        )

    def test_the_floor_still_applies(self):
        # Permuting endlessly cannot drive a win below the floor.
        assert calculate_score("win", 0, 0, False, False, misplaced_guesses=100) == SCORE_FLOOR

    def test_a_loss_is_still_zero(self):
        assert calculate_score("loss", 0, 0, False, False, misplaced_guesses=3) == 0

    def test_existing_scores_do_not_move(self):
        # misplaced_guesses defaults to 0, which is why the 352 frozen parity
        # cases still pass. Adding a penalty must not silently rewrite what
        # anybody already earned.
        assert calculate_score("win", 45, 1, True, False) == calculate_score(
            "win", 45, 1, True, False, misplaced_guesses=0
        )

    def test_the_breakdown_reports_it_separately(self):
        breakdown = score_breakdown(
            time_seconds=0, wrong_guesses=0, hint_used=False, hard_mode=False, misplaced_guesses=3
        )
        assert breakdown["misplaced_pen"] == 3 * MISPLACED_PEN
        assert breakdown["wrong_pen"] == 0
