"""Scoring, ported from frontend/src/lib/scoring.js.

Phase 0 moves scoring server-side so a score cannot be invented by the client.
Until the frontend switches over, both implementations exist and must agree
exactly -- otherwise the changeover silently rewrites everyone's numbers.

tests/test_scoring.py asserts that against fixtures generated by *executing*
scoring.js, not by re-reading it. Regenerate them with:

    node backend/tests/fixtures/generate_scoring_parity.mjs \\
        > backend/tests/fixtures/scoring_parity.json

Any change here must be made in scoring.js too, until chore/lock-down-writes
deletes the JS copy.
"""

BASE = 1000
TIME_GRACE = 30  # free seconds before the time penalty starts, when length is unknown

# Free seconds, scaled to the work.
#
# A flat grace charges a nine-stop career for the seven extra team names it has
# to type. That is not thinking time, it is mechanics, and the clock should not
# bill for it. Worth about fifty points on the longest careers -- real, and
# much smaller than it feels, which is why it is the least of the three things
# that made long careers harsher.
BASE_TIME_GRACE = 15
TIME_GRACE_PER_TEAM = 10
TIME_RATE = 1  # points lost per second after the grace period
# The clock runs on the server and keeps running while somebody is away -- it
# has to, because a browser that could say "do not count that" is a browser that
# can claim a perfect time, which is the trust Phase 0 removed.
#
# What is bounded instead is the damage. Time can take 600 of the 1000, which is
# a lot: a clean game that took a long while still scores 400, and speed is
# still worth more than anything else on this list. But a daily started at
# breakfast and finished at lunch is no longer worth the same as a daily
# abandoned, which is what an uncapped clock made it.
#
# 600 is reached at 10.5 minutes of play. Past that the clock is cosmetic.
MAX_TIME_PENALTY = 600
HINT_PEN = 150
WRONG_PEN = 100
# A misplacement is not a wrong answer -- the team is right, the slot is not --
# so it costs no life. It still costs points, because a free yellow would let
# anyone who knows the teams permute them until everything turned green, and the
# order is the game.
MISPLACED_PEN = 25
SCORE_FLOOR = 100  # minimum for any win, applied *before* the hard multiplier
HARD_MULTIPLIER = 1.5


def time_grace(team_count=None):
    """How long a career of this length may take before the clock starts biting.

    Falls back to the flat value when the length is not given, which keeps the
    parity fixture -- 352 recorded cases that cannot be regenerated, because the
    JavaScript original is gone -- meaning exactly what it meant.
    """
    if not team_count:
        return TIME_GRACE
    return BASE_TIME_GRACE + TIME_GRACE_PER_TEAM * team_count


def calculate_score(
    result,
    time_seconds,
    wrong_guesses,
    hint_used,
    hard_mode,
    misplaced_guesses=0,
    team_count=None,
):
    """Score one finished game. A loss is always zero."""
    if result != "win":
        return 0

    time_pen = min(max(0, time_seconds - time_grace(team_count)) * TIME_RATE, MAX_TIME_PENALTY)
    hint_pen = HINT_PEN if hint_used else 0
    wrong_pen = wrong_guesses * WRONG_PEN
    misplaced_pen = misplaced_guesses * MISPLACED_PEN

    base_score = max(SCORE_FLOOR, BASE - time_pen - hint_pen - wrong_pen - misplaced_pen)

    # The floor is applied before the multiplier, so the lowest possible
    # hard-mode win is 150 rather than 100. Moving the multiplier inside the
    # max() would silently change every hard-mode score.
    if hard_mode:
        return _js_round(base_score * HARD_MULTIPLIER)

    return base_score


def _js_round(value):
    """Round half away from zero, the way JavaScript's Math.round does.

    Python's round() is banker's rounding: round(2.5) is 2, but Math.round(2.5)
    is 3. Every score here is positive and the multiplier only ever produces a
    .0 or .5, so this is the half that matters.
    """
    return int(value + 0.5)


def score_breakdown(time_seconds, wrong_guesses, hint_used, hard_mode, misplaced_guesses=0):
    """The parts of the score, for display. Does not apply the floor."""
    return {
        "base": BASE,
        "time_pen": min(max(0, time_seconds - TIME_GRACE) * TIME_RATE, MAX_TIME_PENALTY),
        "hint_pen": HINT_PEN if hint_used else 0,
        "wrong_pen": wrong_guesses * WRONG_PEN,
        "misplaced_pen": misplaced_guesses * MISPLACED_PEN,
        "hard_mode": bool(hard_mode),
    }


def calculate_streaks(results):
    """Current and best win streaks. `results` is newest-first, as Supabase returns."""
    current = 0
    for result in results:
        if result == "win":
            current += 1
        else:
            break

    best = 0
    run = 0
    for result in reversed(results):
        if result == "win":
            run += 1
            best = max(best, run)
        else:
            run = 0

    return {"current": current, "best": best}
