"""Scoring, ported from frontend/src/lib/scoring.js.

Phase 0 moves scoring server-side so a score cannot be invented by the client.
Until the frontend switches over, both implementations exist and must agree
exactly -- otherwise the changeover silently rewrites everyone's numbers.

tests/test_scoring.py asserts that against fixtures generated by *executing*
scoring.js, not by re-reading it. Regenerate them with:

    node backend/tests/fixtures/generate_scoring_parity.mjs \\
        > backend/tests/fixtures/scoring_parity.json

Any change here must be made in scoring.js too, until chore/lock-down-writes
deletes the JS copy.
"""

BASE = 1000
TIME_GRACE = 30  # free seconds before the time penalty starts
TIME_RATE = 1  # points lost per second after the grace period
HINT_PEN = 150
WRONG_PEN = 100
# A misplacement is not a wrong answer -- the team is right, the slot is not --
# so it costs no life. It still costs points, because a free yellow would let
# anyone who knows the teams permute them until everything turned green, and the
# order is the game.
MISPLACED_PEN = 25
SCORE_FLOOR = 100  # minimum for any win, applied *before* the hard multiplier
HARD_MULTIPLIER = 1.5


def calculate_score(result, time_seconds, wrong_guesses, hint_used, hard_mode, misplaced_guesses=0):
    """Score one finished game. A loss is always zero."""
    if result != "win":
        return 0

    time_pen = max(0, time_seconds - TIME_GRACE) * TIME_RATE
    hint_pen = HINT_PEN if hint_used else 0
    wrong_pen = wrong_guesses * WRONG_PEN
    misplaced_pen = misplaced_guesses * MISPLACED_PEN

    base_score = max(SCORE_FLOOR, BASE - time_pen - hint_pen - wrong_pen - misplaced_pen)

    # The floor is applied before the multiplier, so the lowest possible
    # hard-mode win is 150 rather than 100. Moving the multiplier inside the
    # max() would silently change every hard-mode score.
    if hard_mode:
        return _js_round(base_score * HARD_MULTIPLIER)

    return base_score


def _js_round(value):
    """Round half away from zero, the way JavaScript's Math.round does.

    Python's round() is banker's rounding: round(2.5) is 2, but Math.round(2.5)
    is 3. Every score here is positive and the multiplier only ever produces a
    .0 or .5, so this is the half that matters.
    """
    return int(value + 0.5)


def score_breakdown(time_seconds, wrong_guesses, hint_used, hard_mode, misplaced_guesses=0):
    """The parts of the score, for display. Does not apply the floor."""
    return {
        "base": BASE,
        "time_pen": max(0, time_seconds - TIME_GRACE) * TIME_RATE,
        "hint_pen": HINT_PEN if hint_used else 0,
        "wrong_pen": wrong_guesses * WRONG_PEN,
        "misplaced_pen": misplaced_guesses * MISPLACED_PEN,
        "hard_mode": bool(hard_mode),
    }


def calculate_streaks(results):
    """Current and best win streaks. `results` is newest-first, as Supabase returns."""
    current = 0
    for result in results:
        if result == "win":
            current += 1
        else:
            break

    best = 0
    run = 0
    for result in reversed(results):
        if result == "win":
            run += 1
            best = max(best, run)
        else:
            run = 0

    return {"current": current, "best": best}
